name: Daily Balance Notification

on:
  schedule:
    - cron: "0 17 * * *"  # 11 PM Bangladesh time (UTC+6)
  workflow_dispatch:       # <-- enables manual trigger

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch Balance
        id: fetch
        run: |
          response=$(curl --insecure -s "https://prepaid.desco.org.bd/api/unified/customer/getBalance?accountNo=&meterNo=030410055423")
          balance=$(echo "$response" | jq -r '.data.balance')
          echo "balance=$balance" >> $GITHUB_ENV

      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }} 
          password: ${{ secrets.EMAIL_PASS }} 
          subject: "DESCO Balance Notification"
          to: abusayed.bs23@gmail.com
          from: GitHub Actions <${{ secrets.EMAIL_USER }}>
          body: |
            Hello,
            Your DESCO prepaid meter balance is: **${{ env.balance }}**
            (Checked automatically at 11PM).

      - name: Send Telegram Notification
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          MESSAGE="<b>⚡ DESCO Balance Notification</b><br>
          <i>Checked automatically at 11PM (BD time)</i><br><br>
          <u>Balance Details:</u><br>
          <b>Current Balance:</b> ${{ env.balance }}<br>
          <b>Meter number:</b> 030410055423 <br>
          visit for more infor: <a href='https://prepaid.desco.org.bd/customer/#/customer-info'>View Account Online</a><br>
          <b>credit:</b> sayed021 "
          
          # Escape newlines for Telegram | this will be used when directly using newlines in a message
          # MESSAGE_ESCAPED=$(echo "$MESSAGE" | sed ':a;N;$!ba;s/\n/%0A/g')
          
          # Send the message
          curl -s -X POST "https://api.telegram.org/bot${TELEGRAM_TOKEN}/sendMessage" \
          -d chat_id="${TELEGRAM_CHAT_ID}" \
          -d text="$MESSAGE" \
          -d parse_mode=HTML
